{
 "title": "AWS SNS",
 "description": "Visualize AWS SNS metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "topic",
    "label": "TopicName",
    "query": "dimension_values($region,AWS/SNS,PublishSize,TopicName)"
   }
  ]
 },
 "panels": [
  {
   "title": "NumberOfMessagesPublished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TopicName": "$topic" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfMessagesPublished",
     "namespace": "AWS/SNS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Notifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TopicName": "$topic" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfNotificationsDelivered",
     "namespace": "AWS/SNS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "TopicName": "$topic" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NumberOfNotificationsFailed",
     "namespace": "AWS/SNS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "PublishSize",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TopicName": "$topic" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "PublishSize",
     "namespace": "AWS/SNS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SMSSuccessRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TopicName": "$topic" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "SMSSuccessRate",
     "namespace": "AWS/SNS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/sns/latest/dg/sns-monitoring-using-cloudwatch.html\">AWS CloudWatch SNS documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/581\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}